create database if NOT EXISTS covidrs;
use covidrs;

drop table if EXISTS CASO;
CREATE TABLE CASO
( 
 COD_CASO INTEGER AUTO_INCREMENT PRIMARY KEY,
 COD_IBGE INTEGER,
 COD_REGIAO_COVID INTEGER,
 COD_SEXO INTEGER,  
 COD_FAIXAETARIA INTEGER,  
 COD_CRITERIO INTEGER,  
 COD_EVOLUCAO INTEGER,  
 COD_RACA_COR INTEGER,  
 DATA_CONFIRMACAO VARCHAR(20),  
 DATA_SINTOMAS VARCHAR(20),  
 DATA_INCLUSAO VARCHAR(20),  
 HOSPITALIZADO VARCHAR(20),  
 FEBRE VARCHAR(20),
 TOSSE VARCHAR(20),
 GARGANTA VARCHAR(20),
 DISPNEIA VARCHAR(20),
 OUTROS VARCHAR(20),
 CONDICOES TEXT,
 GESTANTE VARCHAR(20),  
 DATA_INCLUSAO_OBITO VARCHAR(20),  
 DATA_EVOLUCAO_ESTIMADA VARCHAR(20),  
 PROFISSIONAL_SAUDE	 VARCHAR(20),  
 SRAG VARCHAR(20),  
 PES_PRIV_LIBERDADE VARCHAR(20) 
); 

drop table if EXISTS MUNICIPIO;
CREATE TABLE MUNICIPIO 
( 
 COD_IBGE INTEGER PRIMARY KEY,  
 MUNICIPIO VARCHAR(50)
); 

drop table if EXISTS REGIAOCOVID;
CREATE TABLE REGIAOCOVID 
( 
 COD_REGIAO_COVID INTEGER PRIMARY KEY,  
 REGIAO_COVID VARCHAR(50) 
); 

drop table if EXISTS SEXO;
CREATE TABLE SEXO 
( 
 COD_SEXO INTEGER PRIMARY KEY,  
 SEXO VARCHAR(50) 
); 

drop table if EXISTS FAIXAETARIA;
CREATE TABLE FAIXAETARIA 
( 
 COD_FAIXAETARIA INTEGER PRIMARY KEY,  
 FAIXAETARIA VARCHAR(50)  
); 

drop table if EXISTS CRITERIO;
CREATE TABLE CRITERIO 
( 
 COD_CRITERIO INTEGER PRIMARY KEY,  
 CRITERIO VARCHAR(50)
); 

drop table if EXISTS EVOLUCAO;
CREATE TABLE EVOLUCAO 
( 
 COD_EVOLUCAO INTEGER PRIMARY KEY,  
 EVOLUCAO VARCHAR(50)
); 

drop table if EXISTS RACACOR;
CREATE TABLE RACACOR 
( 
 COD_RACA_COR INTEGER PRIMARY KEY,  
 RACA_COR VARCHAR(50)  
); 


ALTER TABLE CASO
ADD CONSTRAINT FK_MUNICIPIO
FOREIGN KEY (COD_IBGE) REFERENCES MUNICIPIO(COD_IBGE);

ALTER TABLE CASO
ADD CONSTRAINT FK_REGIAOCOVID
FOREIGN KEY (COD_REGIAO_COVID) REFERENCES REGIAOCOVID(COD_REGIAO_COVID);

ALTER TABLE CASO
ADD CONSTRAINT FK_SEXO
FOREIGN KEY (COD_SEXO) REFERENCES SEXO(COD_SEXO);

ALTER TABLE CASO
ADD CONSTRAINT FK_FAIXAETARIA
FOREIGN KEY (COD_FAIXAETARIA) REFERENCES FAIXAETARIA(COD_FAIXAETARIA);

ALTER TABLE CASO
ADD CONSTRAINT FK_CRITERIO
FOREIGN KEY (COD_CRITERIO) REFERENCES CRITERIO(COD_CRITERIO);

ALTER TABLE CASO
ADD CONSTRAINT FK_EVOLUCAO
FOREIGN KEY (COD_EVOLUCAO) REFERENCES EVOLUCAO(COD_EVOLUCAO);

ALTER TABLE CASO
ADD CONSTRAINT FK_RACACOR
FOREIGN KEY (COD_RACA_COR) REFERENCES RACACOR(COD_RACA_COR);